// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG-VV5teCOc_0SLcyUDsLQxViAeIco2Oo',
    appId: '1:308753828467:web:78f3b25c3af000e9a9f806',
    messagingSenderId: '308753828467',
    projectId: 'ex-chat-app-7f6ba',
    authDomain: 'ex-chat-app-7f6ba.firebaseapp.com',
    storageBucket: 'ex-chat-app-7f6ba.firebasestorage.app',
    measurementId: 'G-MX99SKP3QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtD4yfnUPBTOlHaJWiJW0P67_cYYT3-6I',
    appId: '1:308753828467:android:30001a403c47a192a9f806',
    messagingSenderId: '308753828467',
    projectId: 'ex-chat-app-7f6ba',
    storageBucket: 'ex-chat-app-7f6ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ54lJQZfs5oNuj-V16QDANHtH3Sf6HRA',
    appId: '1:308753828467:ios:80c80679548c2e6ea9f806',
    messagingSenderId: '308753828467',
    projectId: 'ex-chat-app-7f6ba',
    storageBucket: 'ex-chat-app-7f6ba.firebasestorage.app',
    iosBundleId: 'com.example.exChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ54lJQZfs5oNuj-V16QDANHtH3Sf6HRA',
    appId: '1:308753828467:ios:80c80679548c2e6ea9f806',
    messagingSenderId: '308753828467',
    projectId: 'ex-chat-app-7f6ba',
    storageBucket: 'ex-chat-app-7f6ba.firebasestorage.app',
    iosBundleId: 'com.example.exChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG-VV5teCOc_0SLcyUDsLQxViAeIco2Oo',
    appId: '1:308753828467:web:4620206a8c9c9c2da9f806',
    messagingSenderId: '308753828467',
    projectId: 'ex-chat-app-7f6ba',
    authDomain: 'ex-chat-app-7f6ba.firebaseapp.com',
    storageBucket: 'ex-chat-app-7f6ba.firebasestorage.app',
    measurementId: 'G-71DR5E1H5T',
  );
}
